#!/bin/bash
#
# A simple script to fetch both CImg and G'MIC updates from the git repo.
#
cd $HOME/work/src/CImg
git checkout master && git pull
git checkout develop && git pull
cd $HOME/work/src/gmic
git checkout master && git pull
git checkout develop && git pull
cd $HOME/work/src/gmic-community
git pull
cd $HOME/work/src/gmic-qt
git pull
cd $HOME/work/src/zart
git pull
